name: flyweight
version: 0.0.1
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  json_rpc_2: '^2.0.1'
  browser: any
  dart_to_js_script_rewriter: '^0.1.0'
dependency_overrides:
  csv: any
#    git: https://github.com/close2/csv
dev_dependencies:
  test: any
transformers:
- dart_to_js_script_rewriter
- $dart2js:
    minify: true
